export class Actions {

    static GET_SERVICE_PROVIDERS_SUCCESS = 'GET_SERVICE_PROVIDERS_SUCCESS';
    static GET_SERVICE_PROVIDERS_LOADING = 'GET_SERVICE_PROVIDERS_LOADING';
    static GET_SERVICE_PROVIDERS_FAILURE = 'GET_SERVICE_PROVIDERS_FAILURE';

    static CREATE_SERVICE_PROVIDERS_SUCCESS = 'CREATE_SERVICE_PROVIDERS_SUCCESS';
    static CREATE_SERVICE_PROVIDERS_LOADING = 'CREATE_SERVICE_PROVIDERS_LOADING';
    static CREATE_SERVICE_PROVIDERS_FAILURE = 'CREATE_SERVICE_PROVIDERS_FAILURE';
    static CREATE_SERVICE_PROVIDERS_RESET = 'CREATE_SERVICE_PROVIDERS_RESET';

    static GET_BRANCH_USERS_SUCCESS = 'GET_BRANCH_USERS_SUCCESS';
    static GET_BRANCH_USERS_LOADING = 'GET_BRANCH_USERS_LOADING';
    static GET_BRANCH_USERS_FAILURE = 'GET_BRANCH_USERS_FAILURE';

    static GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';
    static GET_BRANCHES_LOADING = 'GET_BRANCHES_LOADING';
    static GET_BRANCHES_FAILURE = 'GET_BRANCHES_FAILURE';

    static CREATE_PERMISSION_GROUP_SUCCESS = 'CREATE_PERMISSION_GROUP_SUCCESS';
    static CREATE_PERMISSION_GROUP_LOADING = 'CREATE_PERMISSION_GROUP_LOADING';
    static CREATE_PERMISSION_GROUP_FAILURE = 'CREATE_PERMISSION_GROUP_FAILURE';
    static CREATE_PERMISSION_GROUP_RESET = 'CREATE_PERMISSION_GROUP_RESET';

    static GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
    static GET_POSTS_LOADING = 'GET_POSTS_LOADING';
    static GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

    static GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
    static GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
    static GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

    static GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
    static GET_SERVICES_LOADING = 'GET_SERVICES_LOADING';
    static GET_SERVICES_FAILURE = 'GET_SERVICES_FAILURE';

    static MODIFY_PRODUCT_SUCCESS = 'MODIFY_PRODUCT_SUCCESS';
    static MODIFY_PRODUCT_LOADING = 'MODIFY_PRODUCT_LOADING';
    static MODIFY_PRODUCT_FAILURE = 'MODIFY_PRODUCT_FAILURE';
    static MODIFY_PRODUCT_RESET = 'MODIFY_PRODUCT_RESET';

    static MODIFY_SERVICE_SUCCESS = 'MODIFY_SERVICE_SUCCESS';
    static MODIFY_SERVICE_LOADING = 'MODIFY_SERVICE_LOADING';
    static MODIFY_SERVICE_FAILURE = 'MODIFY_SERVICE_FAILURE';
    static MODIFY_SERVICE_RESET = 'MODIFY_SERVICE_RESET';

    static MODIFY_POST_SUCCESS = 'MODIFY_POST_SUCCESS';
    static MODIFY_POST_LOADING = 'MODIFY_POST_LOADING';
    static MODIFY_POST_FAILURE = 'MODIFY_POST_FAILURE';
    static MODIFY_POST_RESET = 'MODIFY_POST_RESET';

    static CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
    static CREATE_SERVICE_LOADING = 'CREATE_SERVICE_LOADING';
    static CREATE_SERVICE_FAILURE = 'CREATE_SERVICE_FAILURE';
    static CREATE_SERVICE_RESET = 'CREATE_SERVICE_RESET';

    static SIGN_SUCCESS = 'SIGN_SUCCESS';
    static SIGN_LOADING = 'SIGN_LOADING';
    static SIGN_FAILURE = 'SIGN_FAILURE';
    static SIGN_RESET = 'SIGN_RESET';

    static CREATE_HIRING_REQUEST_SUCCESS = 'CREATE_HIRING_REQUEST_SUCCESS';
    static CREATE_HIRING_REQUEST_LOADING = 'CREATE_HIRING_REQUEST_LOADING';
    static CREATE_HIRING_REQUEST_FAILURE = 'CREATE_HIRING_REQUEST_FAILURE';
    static CREATE_HIRING_REQUEST_RESET = 'CREATE_HIRING_REQUEST_RESET';

    static UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
    static UPDATE_USER_LOADING = 'UPDATE_USER_LOADING';
    static UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
    static UPDATE_USER_RESET = 'UPDATE_USER_RESET';

    static CREATE_BRANCH_SUCCESS = 'CREATE_BRANCH_SUCCESS';
    static CREATE_BRANCH_LOADING = 'CREATE_BRANCH_LOADING';
    static CREATE_BRANCH_FAILURE = 'CREATE_BRANCH_FAILURE';
    static CREATE_BRANCH_RESET = 'CREATE_BRANCH_RESET';

    static CREATE_JOB_OFFER_SUCCESS = 'CREATE_JOB_OFFER_SUCCESS';
    static CREATE_JOB_OFFER_LOADING = 'CREATE_JOB_OFFER_LOADING';
    static CREATE_JOB_OFFER_FAILURE = 'CREATE_JOB_OFFER_FAILURE';
    static CREATE_JOB_OFFER_RESET = 'CREATE_JOB_OFFER_RESET';

    static MODIFY_USER_BRANCHES_SUCCESS = 'MODIFY_USER_BRANCHES_SUCCESS';
    static MODIFY_USER_BRANCHES_LOADING = 'MODIFY_USER_BRANCHES_LOADING';
    static MODIFY_USER_BRANCHES_FAILURE = 'MODIFY_USER_BRANCHES_FAILURE';
    static MODIFY_USER_BRANCHES_RESET = 'MODIFY_USER_BRANCHES_RESET';

    static MODIFY_USER_ROLE_SUCCESS = 'MODIFY_USER_ROLE_SUCCESS';
    static MODIFY_USER_ROLE_LOADING = 'MODIFY_USER_ROLE_LOADING';
    static MODIFY_USER_ROLE_FAILURE = 'MODIFY_USER_ROLE_FAILURE';
    static MODIFY_USER_ROLE_RESET = 'MODIFY_USER_ROLE_RESET';

    static MODIFY_PERMISSION_GROUP_SUCCESS = 'MODIFY_PERMISSION_GROUP_SUCCESS';
    static MODIFY_PERMISSION_GROUP_LOADING = 'MODIFY_PERMISSION_GROUP_LOADING';
    static MODIFY_PERMISSION_GROUP_FAILURE = 'MODIFY_PERMISSION_GROUP_FAILURE';
    static MODIFY_PERMISSION_GROUP_RESET = 'MODIFY_PERMISSION_GROUP_RESET';

    static GET_PERMISSION_GROUPS_SUCCESS = 'GET_PERMISSION_GROUPS_SUCCESS';
    static GET_PERMISSION_GROUPS_LOADING = 'GET_PERMISSION_GROUPS_LOADING';
    static GET_PERMISSION_GROUPS_FAILURE = 'GET_PERMISSION_GROUPS_FAILURE';

    static GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
    static GET_USERS_LOADING = 'GET_USERS_LOADING';
    static GET_USERS_FAILURE = 'GET_USERS_FAILURE';

    static GET_USER_SUCCESS = 'GET_USER_SUCCESS';
    static GET_USER_LOADING = 'GET_USER_LOADING';
    static UNAUTHORIZED_FAILURE = 'UNAUTHORIZED_FAILURE';

    static GET_HIRING_REQUESTS_SUCCESS = 'GET_HIRING_REQUESTS_SUCCESS';
    static GET_HIRING_REQUESTS_LOADING = 'GET_HIRING_REQUESTS_LOADING';
    static GET_HIRING_REQUESTS_FAILURE = 'GET_HIRING_REQUESTS_FAILURE';

    static MODIFY_HIRING_REQUESTS_SUCCESS = 'MODIFY_HIRING_REQUESTS_SUCCESS';
    static MODIFY_HIRING_REQUESTS_LOADING = 'MODIFY_HIRING_REQUESTS_LOADING';
    static MODIFY_HIRING_REQUESTS_FAILURE = 'MODIFY_HIRING_REQUESTS_FAILURE';
    static MODIFY_HIRING_REQUESTS_RESET = 'MODIFY_HIRING_REQUESTS_RESET';

    static GET_JOB_OFFERS_SUCCESS = 'GET_JOB_OFFERS_SUCCESS';
    static GET_JOB_OFFERS_LOADING = 'GET_JOB_OFFERS_LOADING';
    static GET_JOB_OFFERS_FAILURE = 'GET_JOB_OFFERS_FAILURE';

    static MODIFY_JOB_OFFERS_SUCCESS = 'MODIFY_JOB_OFFERS_SUCCESS';
    static MODIFY_JOB_OFFERS_LOADING = 'MODIFY_JOB_OFFERS_LOADING';
    static MODIFY_JOB_OFFERS_FAILURE = 'MODIFY_JOB_OFFERS_FAILURE';
    static MODIFY_JOB_OFFERS_RESET = 'MODIFY_JOB_OFFERS_RESET';

    static GET_SERVICE_PROVIDER_USERS_SUCCESS = 'GET_SERVICE_PROVIDER_USERS_SUCCESS';
    static GET_SERVICE_PROVIDER_USERS_LOADING = 'GET_SERVICE_PROVIDER_USERS_LOADING';
    static GET_SERVICE_PROVIDER_USERS_FAILURE = 'GET_SERVICE_PROVIDER_USERS_FAILURE';

    static GET_CEOS_SUCCESS = 'GET_CEOS_SUCCESS';
    static GET_CEOS_LOADING = 'GET_CEOS_LOADING';
    static GET_CEOS_FAILURE = 'GET_CEOS_FAILURE';

    static GET_USER_SERVICE_PROVIDERS_SUCCESS = 'GET_USER_SERVICE_PROVIDERS_SUCCESS';
    static GET_USER_SERVICE_PROVIDERS_LOADING = 'GET_USER_SERVICE_PROVIDERS_LOADING';
    static GET_USER_SERVICE_PROVIDERS_FAILURE = 'GET_USER_SERVICE_PROVIDERS_FAILURE';

    static GET_BRANCH_BY_ID_SUCCESS = 'GET_BRANCH_BY_ID_SUCCESS';
    static GET_BRANCH_BY_ID_LOADING = 'GET_BRANCH_BY_ID_LOADING';
    static GET_BRANCH_BY_ID_FAILURE = 'GET_BRANCH_BY_ID_FAILURE';

    static GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
    static GET_USER_BY_ID_LOADING = 'GET_USER_BY_ID_LOADING';
    static GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE';

    static GET_SERVICE_PROVIDER_BY_ID_SUCCESS = 'GET_SERVICE_PROVIDER_BY_ID_SUCCESS';
    static GET_SERVICE_PROVIDER_BY_ID_LOADING = 'GET_SERVICE_PROVIDER_BY_ID_LOADING';
    static GET_SERVICE_PROVIDER_BY_ID_FAILURE = 'GET_SERVICE_PROVIDER_BY_ID_FAILURE';

}

export class Operations {
    static CREATE = 'CREATE';
    static EDIT = 'EDIT';
    static REMOVE = 'REMOVE';
    static REJECT = 'REJECT';
    static CANCEL = 'CANCEL';
    static ACCEPT = 'ACCEPT';
    static LOGIN = 'LOGIN';
}